name: Java CI
run-name: Builds and tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Build image
        run: mvn jib:dockerBuild -Djib.allowInsecureRegistries=true
      - name: Define image tags
        id: meta
        uses: actions/docker-metadata-action@v3
        with:
          images: localhost:5000/kubernetes
          tags: ${{ github.run_number }}